experiment_name: 'AFLoc_pretrain'
trial_name: 
phase: 'pretrain'
lightning:
    trainer:
       gpus: '0,1'
       max_epochs: 5
       accelerator: 'dp'
       gradient_clip_val: 0.25
       lr: 0.00002
       precision: 16
       benchmark: false
       deterministic: true
    checkpoint_callback:
        monitor: 'val_loss'
        dirpath: './data/ckpt'
        save_last: false 
        mode: min
        save_top_k: 5
    early_stopping_callback:
        monitor: 'val_loss'
        min_delta: 0.00
        patience: 10
        verbose: False
        mode: 'min'
    logger:
        logger_type: 'WandbLogger'
        save_dir: './data/'
        project: 'AFLoc'
model:
    norm: false
    afloc: 
        temp1: 4.0
        temp2: 5.0
        temp3: 10.0
        use_global_report_loss: true
        global_report_loss_weight: 1.0

        use_local_sent_loss: true
        local_sent_loss_weight: 1.0

        use_local_word_loss: true
        local_word_loss_weight: 1.0

    vision:
        model_name: 'resnet_50'
        freeze_cnn: false
        pretrained: true
        
    text:  
        bert_type: "emilyalsentzer/Bio_ClinicalBERT"
        last_n_layers: 4
        aggregate_method: 'sum'
        norm: false
        embedding_dim: 768
        freeze_bert: false
        agg_tokens: true
        take_sent_as_units: true
data: 
    dataset: ['mimic']
    view: 'Frontal'
    missing_value_mode: 0
    text: 
      word_num: 97
      captions_per_image: 5
      full_report: true
      random_combine: true
      random_combine_mode: 1
      random_num: true
    image:
        imsize: 256
transforms: 
    use_medklip: false
    norm: 'half'
    center_crop:
        crop_size: 224
    random_crop:
        crop_size: 224
train: 
    update_interval: 1000
    batch_size: 128
    num_workers: 8
    nvis: 8
    rand_vis: false 
    optimizer: 
        name: 'Adam'
        weight_decay: 1e-6
    scheduler: 
        name: 'step'
        monitor: 'val_loss'
        interval: 'epoch'
        frequency: 1
        step_size: 1
        gamma: 0.9
    seeds: [1, 2]
test:
    update_interval: 1